Repository ryanclark/karma-webpack, pull requests merged in 2018-02, with the labels that each got.

#287 fix(karma-webpack): correctly coalesce `idx` (`{Number}`) in filepaths
  src/karma-webpack.js
Labels: pr_action: Review, priority: 2 (urgent), semver: Patch, severity: 3 (broken), type: Bug

#293 fix(karma-webpack): correctly escape `{Regex}` in custom file handler
  src/karma-webpack.js
Labels: pr_action: Review, priority: 4 (important), semver: Patch, status: Pending, type: Bug

#294 build(package): don't generate source maps for release (`build:release`)
  package.json
Labels: pr_action: Review, semver: Patch, status: Pending, type: Build

#301 fix(package): add `webpack >= v4.0.0` (`peerDependencies`)
  package.json
Labels: pr_action: Review, priority: 3 (required), semver: Patch, severity: 4 (inconvenient), type: Bug

#303 style(src/): fix linting errors
  .gitignore
  src/karma-webpack.js
  src/mocha-env-loader.js
Labels: semver: Patch, status: Approved, type: Style

#302 ci(.travis): update CI config
  .travis.yml
Labels: semver: Patch, status: Approved, type: CI

#304 fix(package): repository URL typo
  package.json
Labels: semver: Patch, status: Approved, type: Bug

#309 fix(package): downgrade `source-map` v0.7.0...0.5.6
  package.json
Labels: semver: Patch, status: Approved, type: Bug

#310 fix(package): add `babel-runtime` (`devDependencies`)
  package-lock.json
  package.json
Labels: semver: Patch, status: Approved, type: Bug

#312 fix(package): use `babel-runtime` is a `dependency` (`dependencies`)
  package.json
Labels: semver: Patch, status: Approved, type: Bug
