Repository ryanclark/karma-webpack, pull requests merged in 2018-11, with the labels that each got.

#361 [v4.x] fix(karma-webpack): handle multiple outputs correctly
  src/karma-webpack.js
Labels: pr_action: Review, priority: 2 (urgent), semver: Patch, severity: 2 (regression), status: Pending, type: Bug

#360 fix(karma-webpack): handle `outputPath` correctly
  src/karma-webpack.js
Labels: pr_action: Review, priority: 2 (urgent), semver: Patch, severity: 3 (broken), status: Pending, type: Bug

#367 fix(npm packaging): restore prepare script in package.json so that npm install from github works
  package.json
Labels: pr_action: Merge ready, priority: 4 (important), severity: 4 (inconvenient), type: Build

#364 refactor(karma-webpack): Remove lodash from dependencies
  package-lock.json
  package.json
  src/karma-webpack.js
Labels: pr_action: Merge ready, priority: 4 (important), semver: Patch, type: Refactor

#373 fix(karma-webpack): Fix publicPath to be Windows-compatible
  src/karma-webpack.js
Labels: pr_action: Review, priority: 1 (critical), severity: 2 (regression), type: Bug

#356 feat(karma-webpack): unify `webpack` and `karma` color config
  src/karma-webpack.js
  test/plugin.test.js
Labels: pr_action: Review, priority: 5 (nice to have), semver: Minor, severity: 4 (inconvenient), status: Pending, type: Feature
