Repository ryanclark/karma-webpack, pull requests merged in 2018-09, with the labels that each got.

#340 refactor(package): apply `webpack-defaults`
  .babelrc
  .circleci/config.yml
  .editorconfig
  .eslintignore
  .eslintrc
  .eslintrc.js
  .gitattributes
  .github/CODEOWNERS
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/BUG.md
  .github/ISSUE_TEMPLATE/DOCS.md
  .github/ISSUE_TEMPLATE/FEATURE.md
  .github/ISSUE_TEMPLATE/MODIFICATION.md
  .github/ISSUE_TEMPLATE/SUPPORT.md
  .github/PULL_REQUEST_TEMPLATE.md
  .gitignore
  .prettierrc
  .travis.yml
  appveyor.yml
  codecov.yml
  commitlint.config.js
  package-lock.json
  package.json
  src/index.js
  src/karma-webpack.js
  src/mocha-env-loader.js
  test/integration/karma.config.js
  test/plugin.test.js
  test/unit/es2015Demo.test.js
  test/unit/plugin.test.js
Labels: pr_action: Rework, priority: 3 (required), semver: Patch, severity: 4 (inconvenient), status: Pending, type: Refactor

#341 fix(mocha-env-loader): add `webpack >= v4.0.0` support
  package-lock.json
  package.json
  src/karma-webpack.js
  src/mocha-env-loader.js
Labels: semver: Patch, status: Approved, type: Bug

#354 fix(karma-webpack): normalize `file.path` (`windows`)
  src/karma-webpack.js
Labels: semver: Patch, status: Approved, type: Bug

#351 fix(karma-webpack): normalize paths (`windows`)
  src/karma-webpack.js
Labels: pr_action: Rework, priority: 2 (urgent), semver: Patch, severity: 2 (regression), type: Bug

#338 fix(karma-webpack): don't include `os.tmpdir` (`options.publicPath`)
  src/karma-webpack.js
Labels: semver: Patch, status: Approved, type: Bug
