Repository ryanclark/karma-webpack, pull requests merged in 2019-06, with the labels that each got.

#410 refactor(karma-webpack): fix linting error
  src/karma-webpack.js
Labels: pr_action: Review, type: Refactor

#409 chore(package): drop node v6 support
  .circleci/config.yml
  package.json
Labels: pr_action: Review

#411 refactor(package): add more keywords for npm
  package.json
Labels: pr_action: Review, type: Refactor

#417 fix(package): point to dist instead of lib
  package.json
Labels: pr_action: Review, priority: 1 (critical), severity: 2 (regression), type: Bug

#418 fix(karma-webpack): don't error when webpackMiddleware config not provided
  src/karma-webpack.js
Labels: severity: 2 (regression), status: Approved, type: Bug

#419 test(plugin): add tests to prevent some regressions
  test/plugin.test.js
Labels: pr_action: Review
